### ISSUE TITLE
Getting DB errors, setup not working 

### ISSUE THREAD

**Issue by pavanyogi** [ssi-anik/laravel-broadcast-demo#1]
Hi Anik,

I tried to setup this repo by following all steps given in the readme file. But Setup did not completed successfully. I was getting DB errors. Can you check once and if possible please upload  .env values as well. You can upload in env.example file. 

Thanks

**Comment by ssi-anik** [comment]
what does it say?

**Comment by ssi-anik** [comment]
if it's the docker and db connection issue, then you will have to exec into the php container and run that migrate command.

**Comment by pavanyogi** [comment]
I run the command inside the docker container and setup seems to be in good condition. But socket is not working. We are getting console errors eg: 

It was not getting connected on port 9003. We are getting following console errors on port 9003.
`VM1161:1 GET http://127.0.0.1:9003/socket.io/?EIO=3&transport=polling&t=NDSsJI6 net::ERR_CONNECTION_REFUSED
`
![Screenshot from 2020-07-17 18-17-34](https://user-images.githubusercontent.com/13834016/87789105-19959000-c85c-11ea-9b5d-22196f992119.png)

I looked into Nginx docker conf file and there was mention of 9000 port, so I changed port from 9003 to 9000 (I made these changes in resources/js/bootstrap.js and run the command sudo npm run dev). Port 9000 seems to be correct, but we are getting other errors on this port like:
 `Access to XMLHttpRequest at 'http://127.0.0.1:9000/socket.io/?EIO=3&transport=polling&t=NDSr2VU' from origin 'http://127.0.0.1' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. `
`VM1100:1 GET http://127.0.0.1:9000/socket.io/?EIO=3&transport=polling&t=NDSrCGa net::ERR_FAILED`
![Screenshot from 2020-07-17 18-13-41](https://user-images.githubusercontent.com/13834016/87789182-3cc03f80-c85c-11ea-8349-eb20a33b2dfa.png)

I am using chrome version: `Version 83.0.4103.116 (Official Build) (64-bit)`
Please check if setup is working with chrome-83 in your machine?

**Comment by ssi-anik** [comment]
Okay. Got it.
First of all, socket should be connected to the `echo` server. so, if your echo server is running on (suppose) `4422`, then in your `resources/js/bootstrap.js`, `Echo`'s host should point to that port. so in this case, `9003` should be changed to `4422`. check on which port your echo server is running. The Echo server is the socket server.
Secondly, that port `9000` is for PHP's fpm. it listens through that port.
